version: "3"

# Define global environment variables
x-global-environment:
  &default-env # Create an anchor to reuse
  environment:
    POSTGRES_USERNAME: justin
    POSTGRES_PASSWORD: Pelicano1
    POSTGRES_HOST: cdr2.clr2pnezpd17.us-east-1.rds.amazonaws.com
    POSTGRES_DB: postgres
    AWS_BUCKET: xabi-udacity-2
    AWS_REGION: us-east-1
    AWS_PROFILE: default
    JWT_SECRET: testing
    URL: http://localhost:8100
    AWS_ACCESS_KEY_ID: ASIAZGZ4MHOBMKFTFZBA
    AWS_SECRET_ACCESS_KEY: ccVptSzvx27XVJeTKWaW1M9canuGbH5JBAGMDbAb
    AWS_DEFAULT_REGION: us-east-1


services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    <<: *default-env # Reuse global environment variables
  backend-feed:
    image: udagram-api-feed
    volumes:
      - ${USERPROFILE}/.aws:/root/.aws
    <<: *default-env # Reuse global environment variables
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"
    <<: *default-env # Reuse global environment variables